<?php

/**
 * @file
 * Contains qr_code.module.
 */

/**
 * Implements hook_theme().
 *
 * @see https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Render!theme.api.php/function/hook_theme/8.9.x
 */
function qr_code_theme() {
  return [
    'qr_themeable_block' => [
      'variables' => [
        'content' => NULL,
        'loggedin' => NULL,
        'gen_error' => NULL,
        'event' => NULL,
        'coupon_code' => NULL,
        'url' => NULL,
        'how_to_use' => NULL,
        'terms_conditions' => NULL,
        'event_date' => NULL,
        'event_time' => NULL,
        'already_redeemed' => NULL,
      ],
      'render element' => 'children',
    ],
    'qr_scan_pass' => [
      'variables' => [
        'content' => NULL,
        'event' => NULL,
        'event_date' => NULL,
        'event_time' => NULL,
        'snap' => NULL,
      ],
      'render element' => 'children',
    ],
    'qr_scan_pass_error' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
    'checkin_page' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}