system_match: "views_block:who_s_new-block_1\r\nviews_block:who_s_online-who_s_online_block\t\r\n"
system_prefix: ''
system_regex: ''
system_negate: false
layout_match: "local_tasks_block\r\nlocal_actions_block\r\nviews_block:comments_recent-block_1\r\nhelp_block\r\nwebform_access_group_entity\r\nwebform_submission_limit_block\r\nsystem_breadcrumb_block\r\nsystem_powered_by_block\r\nnode_syndicate_block\r\nsystem_messages_block\r\nsystem_main_block\r\nviews_block:content_recent-block_1\r\nshortcuts\r\nsystem_menu_block:footer\r\nsystem_menu_block:admin\r\nsystem_menu_block:tools\r\nsystem_menu_block:main\r\nsystem_menu_block:account\r\nsystem_branding_block"
layout_prefix: ''
layout_regex: ''
layout_negate: false
_core:
  default_config_hash: G8QQmvYdIX4fGt1SxVZIFa0KjWFS4FbLlNlt6N19qIM
