features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://racf_logo_0.png'
logo_style: branding
favicon:
  use_default: 1
